// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type NotificationType string

const (
	NotificationTypePRICEDROP NotificationType = "PRICE_DROP"
	NotificationTypeRESTOCK   NotificationType = "RESTOCK"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Notification struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
	WatchlistID uuid.UUID
	Type        NotificationType
	OldPrice    sql.NullString
	NewPrice    sql.NullString
	Read        bool
	CreatedAt   time.Time
}

type PriceHistory struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Price     string
	InStock   bool
	ScrapedAt time.Time
}

type Product struct {
	ID            uuid.UUID
	Slug          string
	Name          string
	Sku           string
	ExternalID    string
	Category      string
	Url           string
	ImageUrl      string
	CurrentPrice  string
	Currency      string
	InStock       bool
	LastScrapedAt time.Time
	CreatedAt     sql.NullTime
}

type Token struct {
	Hash   string
	UserID uuid.UUID
	Expiry time.Time
	Scope  string
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Activated    sql.NullBool
	NotifyEmail  sql.NullBool
	NotifyPush   sql.NullBool
	Tier         sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Watchlist struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	ProductID    uuid.UUID
	AlertSale    bool
	AlertRestock bool
	CreatedAt    sql.NullTime
}
