// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
  AND ($2::boolean IS NULL OR read = $2)
`

type CountNotificationsByUserParams struct {
	UserID     uuid.UUID
	ReadFilter sql.NullBool
}

func (q *Queries) CountNotificationsByUser(ctx context.Context, arg CountNotificationsByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsByUser, arg.UserID, arg.ReadFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationsByUser = `-- name: GetNotificationsByUser :many
SELECT
  n.id,
  n.user_id,
  n.product_id,
  n.watchlist_id,
  n.type,
  n.old_price,
  n.new_price,
  n.read,
  n.created_at,
  p.name       AS product_name,
  p.image_url  AS product_image_url,
  p.slug       AS product_slug
FROM notifications n
INNER JOIN products p ON p.id = n.product_id
WHERE n.user_id = $1
  AND ($4::boolean IS NULL OR n.read = $4)
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsByUserParams struct {
	UserID     uuid.UUID
	Limit      int32
	Offset     int32
	ReadFilter sql.NullBool
}

type GetNotificationsByUserRow struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ProductID       uuid.UUID
	WatchlistID     uuid.UUID
	Type            NotificationType
	OldPrice        sql.NullString
	NewPrice        sql.NullString
	Read            bool
	CreatedAt       time.Time
	ProductName     string
	ProductImageUrl string
	ProductSlug     string
}

func (q *Queries) GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]GetNotificationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByUser,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.ReadFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsByUserRow
	for rows.Next() {
		var i GetNotificationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.WatchlistID,
			&i.Type,
			&i.OldPrice,
			&i.NewPrice,
			&i.Read,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductImageUrl,
			&i.ProductSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (user_id, product_id, watchlist_id, type, old_price, new_price)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, product_id, watchlist_id, type, old_price, new_price, read, created_at
`

type InsertNotificationParams struct {
	UserID      uuid.UUID
	ProductID   uuid.UUID
	WatchlistID uuid.UUID
	Type        NotificationType
	OldPrice    sql.NullString
	NewPrice    sql.NullString
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.UserID,
		arg.ProductID,
		arg.WatchlistID,
		arg.Type,
		arg.OldPrice,
		arg.NewPrice,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.WatchlistID,
		&i.Type,
		&i.OldPrice,
		&i.NewPrice,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read = true
WHERE user_id = $1 AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, product_id, watchlist_id, type, old_price, new_price, read, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.WatchlistID,
		&i.Type,
		&i.OldPrice,
		&i.NewPrice,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
