// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_history.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPriceHistoryByProduct = `-- name: GetPriceHistoryByProduct :many
SELECT id, product_id, price, in_stock, scraped_at
FROM price_history
WHERE product_id = $1
ORDER BY scraped_at DESC
LIMIT $2
`

type GetPriceHistoryByProductParams struct {
	ProductID uuid.UUID
	Limit     int32
}

func (q *Queries) GetPriceHistoryByProduct(ctx context.Context, arg GetPriceHistoryByProductParams) ([]PriceHistory, error) {
	rows, err := q.db.QueryContext(ctx, getPriceHistoryByProduct, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceHistory
	for rows.Next() {
		var i PriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Price,
			&i.InStock,
			&i.ScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPriceHistory = `-- name: InsertPriceHistory :one
INSERT INTO price_history (product_id, price, in_stock)
VALUES ($1, $2, $3)
RETURNING id, product_id, price, in_stock, scraped_at
`

type InsertPriceHistoryParams struct {
	ProductID uuid.UUID
	Price     string
	InStock   bool
}

func (q *Queries) InsertPriceHistory(ctx context.Context, arg InsertPriceHistoryParams) (PriceHistory, error) {
	row := q.db.QueryRowContext(ctx, insertPriceHistory, arg.ProductID, arg.Price, arg.InStock)
	var i PriceHistory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Price,
		&i.InStock,
		&i.ScrapedAt,
	)
	return i, err
}
