// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProductByExternalID = `-- name: GetProductByExternalID :one
SELECT id, slug, name, sku, external_id, category, url, image_url, current_price, currency, in_stock, last_scraped_at, created_at FROM products WHERE external_id = $1
`

func (q *Queries) GetProductByExternalID(ctx context.Context, externalID string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByExternalID, externalID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Sku,
		&i.ExternalID,
		&i.Category,
		&i.Url,
		&i.ImageUrl,
		&i.CurrentPrice,
		&i.Currency,
		&i.InStock,
		&i.LastScrapedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, name, slug, sku, last_scraped_at, external_id, category, url, image_url, currency, current_price, in_stock FROM products 
WHERE id=$1
`

type GetProductByIdRow struct {
	ID            uuid.UUID
	Name          string
	Slug          string
	Sku           string
	LastScrapedAt time.Time
	ExternalID    string
	Category      string
	Url           string
	ImageUrl      string
	Currency      string
	CurrentPrice  string
	InStock       bool
}

func (q *Queries) GetProductById(ctx context.Context, id uuid.UUID) (GetProductByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i GetProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sku,
		&i.LastScrapedAt,
		&i.ExternalID,
		&i.Category,
		&i.Url,
		&i.ImageUrl,
		&i.Currency,
		&i.CurrentPrice,
		&i.InStock,
	)
	return i, err
}

const getStaleProducts = `-- name: GetStaleProducts :many
SELECT DISTINCT p.id, p.slug, p.name, p.sku, p.external_id, p.category, p.url, p.image_url, p.current_price, p.currency, p.in_stock, p.last_scraped_at, p.created_at
FROM products p
INNER JOIN watchlist w ON w.product_id = p.id
WHERE p.last_scraped_at < now() - interval '5 minutes'
`

func (q *Queries) GetStaleProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getStaleProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Sku,
			&i.ExternalID,
			&i.Category,
			&i.Url,
			&i.ImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.InStock,
			&i.LastScrapedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (
    slug,
    name,
    sku,
    external_id,
    category,
    url,
    image_url,
    current_price,
    currency,
    in_stock,
    last_scraped_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, slug, name, sku, external_id, category, url, image_url, current_price, currency, in_stock, last_scraped_at, created_at
`

type InsertProductParams struct {
	Slug          string
	Name          string
	Sku           string
	ExternalID    string
	Category      string
	Url           string
	ImageUrl      string
	CurrentPrice  string
	Currency      string
	InStock       bool
	LastScrapedAt time.Time
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.Slug,
		arg.Name,
		arg.Sku,
		arg.ExternalID,
		arg.Category,
		arg.Url,
		arg.ImageUrl,
		arg.CurrentPrice,
		arg.Currency,
		arg.InStock,
		arg.LastScrapedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Sku,
		&i.ExternalID,
		&i.Category,
		&i.Url,
		&i.ImageUrl,
		&i.CurrentPrice,
		&i.Currency,
		&i.InStock,
		&i.LastScrapedAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, slug, name, sku, external_id, category, url, image_url, current_price, currency, in_stock, last_scraped_at, created_at FROM products
WHERE
  ($1::text = '' OR to_tsvector('simple', name) @@ plainto_tsquery('simple', $1::text))
  AND ($2::text = '' OR category = $2::text)
  AND ($3::text = '' OR in_stock = ($3::text)::bool)
  AND ($4::text = '' OR current_price >= ($4::text)::numeric)
  AND ($5::text = '' OR current_price <= ($5::text)::numeric)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type SearchProductsParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 string
	Column5 string
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Sku,
			&i.ExternalID,
			&i.Category,
			&i.Url,
			&i.ImageUrl,
			&i.CurrentPrice,
			&i.Currency,
			&i.InStock,
			&i.LastScrapedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET current_price = $2, in_stock = $3, last_scraped_at = now()
WHERE id = $1
`

type UpdateProductParams struct {
	ID           uuid.UUID
	CurrentPrice string
	InStock      bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct, arg.ID, arg.CurrentPrice, arg.InStock)
	return err
}
