// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteAllForUser = `-- name: DeleteAllForUser :exec
DELETE FROM tokens 
        WHERE scope = $1 AND user_id = $2
`

type DeleteAllForUserParams struct {
	Scope  string
	UserID uuid.UUID
}

func (q *Queries) DeleteAllForUser(ctx context.Context, arg DeleteAllForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteAllForUser, arg.Scope, arg.UserID)
	return err
}

const getUserToken = `-- name: GetUserToken :one
SELECT users.id, users.created_at, users.name, users.email, users.password_hash, users.activated
FROM users
INNER JOIN tokens
ON users.id = tokens.user_id
WHERE tokens.hash = $1
AND tokens.scope = $2 
AND tokens.expiry > $3
`

type GetUserTokenParams struct {
	Hash   string
	Scope  string
	Expiry time.Time
}

type GetUserTokenRow struct {
	ID           uuid.UUID
	CreatedAt    sql.NullTime
	Name         string
	Email        string
	PasswordHash string
	Activated    sql.NullBool
}

func (q *Queries) GetUserToken(ctx context.Context, arg GetUserTokenParams) (GetUserTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserToken, arg.Hash, arg.Scope, arg.Expiry)
	var i GetUserTokenRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Activated,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO tokens (hash, user_id, expiry, scope) 
        VALUES ($1, $2, $3, $4)
`

type InsertTokenParams struct {
	Hash   string
	UserID uuid.UUID
	Expiry time.Time
	Scope  string
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}
