// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, name, email, password_hash, updated_at, activated, tier
        FROM users
        WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID
	CreatedAt    sql.NullTime
	Name         string
	Email        string
	PasswordHash string
	UpdatedAt    sql.NullTime
	Activated    sql.NullBool
	Tier         sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.UpdatedAt,
		&i.Activated,
		&i.Tier,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, created_at, name, email, updated_at, activated, tier
        FROM users
        WHERE id = $1
`

type GetUserByIdRow struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	Name      string
	Email     string
	UpdatedAt sql.NullTime
	Activated sql.NullBool
	Tier      sql.NullString
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.UpdatedAt,
		&i.Activated,
		&i.Tier,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, name, password_hash) 
        VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, activated, notify_email, notify_push, tier, created_at, updated_at
`

type InsertUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Activated,
		&i.NotifyEmail,
		&i.NotifyPush,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotifyEmail = `-- name: UpdateNotifyEmail :exec
UPDATE users SET notify_email = $1 WHERE id = $2
`

type UpdateNotifyEmailParams struct {
	NotifyEmail sql.NullBool
	ID          uuid.UUID
}

func (q *Queries) UpdateNotifyEmail(ctx context.Context, arg UpdateNotifyEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateNotifyEmail, arg.NotifyEmail, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
        SET name = $1, email = $2, password_hash = $3, activated = $4
        WHERE id = $5
`

type UpdateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Activated    sql.NullBool
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Activated,
		arg.ID,
	)
	return err
}
