// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUserWatchlist = `-- name: CountUserWatchlist :one
SELECT COUNT(*) FROM watchlist
WHERE user_id = $1
`

func (q *Queries) CountUserWatchlist(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserWatchlist, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWatchlistEntry = `-- name: DeleteWatchlistEntry :exec
DELETE FROM watchlist
WHERE id = $1 AND user_id = $2
`

type DeleteWatchlistEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteWatchlistEntry(ctx context.Context, arg DeleteWatchlistEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteWatchlistEntry, arg.ID, arg.UserID)
	return err
}

const getWatchersByProduct = `-- name: GetWatchersByProduct :many
SELECT
  w.id          AS watchlist_id,
  w.user_id,
  w.alert_sale,
  w.alert_restock,
  u.email,
  u.name,
  u.notify_email
FROM watchlist w
INNER JOIN users u ON u.id = w.user_id
WHERE w.product_id = $1
`

type GetWatchersByProductRow struct {
	WatchlistID  uuid.UUID
	UserID       uuid.UUID
	AlertSale    bool
	AlertRestock bool
	Email        string
	Name         string
	NotifyEmail  sql.NullBool
}

func (q *Queries) GetWatchersByProduct(ctx context.Context, productID uuid.UUID) ([]GetWatchersByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getWatchersByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWatchersByProductRow
	for rows.Next() {
		var i GetWatchersByProductRow
		if err := rows.Scan(
			&i.WatchlistID,
			&i.UserID,
			&i.AlertSale,
			&i.AlertRestock,
			&i.Email,
			&i.Name,
			&i.NotifyEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchlistByUser = `-- name: GetWatchlistByUser :many
SELECT
  w.id,
  w.user_id,
  w.product_id,
  w.alert_sale,
  w.alert_restock,
  w.created_at,
  p.name        AS product_name,
  p.slug        AS product_slug,
  p.image_url   AS product_image_url,
  p.current_price AS product_current_price,
  p.currency    AS product_currency,
  p.in_stock    AS product_in_stock
FROM watchlist w
INNER JOIN products p ON p.id = w.product_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type GetWatchlistByUserRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ProductID           uuid.UUID
	AlertSale           bool
	AlertRestock        bool
	CreatedAt           sql.NullTime
	ProductName         string
	ProductSlug         string
	ProductImageUrl     string
	ProductCurrentPrice string
	ProductCurrency     string
	ProductInStock      bool
}

func (q *Queries) GetWatchlistByUser(ctx context.Context, userID uuid.UUID) ([]GetWatchlistByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getWatchlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWatchlistByUserRow
	for rows.Next() {
		var i GetWatchlistByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.AlertSale,
			&i.AlertRestock,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductSlug,
			&i.ProductImageUrl,
			&i.ProductCurrentPrice,
			&i.ProductCurrency,
			&i.ProductInStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchlistEntry = `-- name: GetWatchlistEntry :one
SELECT id, user_id, product_id, alert_sale, alert_restock, created_at
FROM watchlist
WHERE id = $1 AND user_id = $2
`

type GetWatchlistEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetWatchlistEntry(ctx context.Context, arg GetWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, getWatchlistEntry, arg.ID, arg.UserID)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AlertSale,
		&i.AlertRestock,
		&i.CreatedAt,
	)
	return i, err
}

const insertWatchlistEntry = `-- name: InsertWatchlistEntry :one
INSERT INTO watchlist (user_id, product_id, alert_sale, alert_restock)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, product_id, alert_sale, alert_restock, created_at
`

type InsertWatchlistEntryParams struct {
	UserID       uuid.UUID
	ProductID    uuid.UUID
	AlertSale    bool
	AlertRestock bool
}

func (q *Queries) InsertWatchlistEntry(ctx context.Context, arg InsertWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, insertWatchlistEntry,
		arg.UserID,
		arg.ProductID,
		arg.AlertSale,
		arg.AlertRestock,
	)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AlertSale,
		&i.AlertRestock,
		&i.CreatedAt,
	)
	return i, err
}

const updateWatchlistEntry = `-- name: UpdateWatchlistEntry :one
UPDATE watchlist
SET
  alert_sale    = $1,
  alert_restock = $2
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, product_id, alert_sale, alert_restock, created_at
`

type UpdateWatchlistEntryParams struct {
	AlertSale    bool
	AlertRestock bool
	ID           uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) UpdateWatchlistEntry(ctx context.Context, arg UpdateWatchlistEntryParams) (Watchlist, error) {
	row := q.db.QueryRowContext(ctx, updateWatchlistEntry,
		arg.AlertSale,
		arg.AlertRestock,
		arg.ID,
		arg.UserID,
	)
	var i Watchlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AlertSale,
		&i.AlertRestock,
		&i.CreatedAt,
	)
	return i, err
}
